# Generated by Django 5.0.6 on 2024-08-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktech', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Offer',
        ),
        migrations.AlterModelTable(
            name='offer',
            table='offer',
        ),
    ]
