# Generated by Django 5.0.6 on 2024-08-25 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ktech', '0002_rename_service_offer_alter_offer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='offer',
            table='offers',
        ),
    ]
