# Generated by Django 5.0.6 on 2024-08-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktech', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='offer',
        ),
        migrations.AddField(
            model_name='order',
            name='offers',
            field=models.ManyToManyField(related_name='orders', to='ktech.offer'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
