# Generated by Django 5.0.6 on 2024-08-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ktech', '0005_remove_order_offer_order_offers_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin',
            field=models.CharField(default='', max_length=255),
        ),
    ]
